ParkingLotServer_APP/ParkingLotServer/admin/controllers.py
import arrow
import jwt
import datetime
from passlib.hash import argon2
from sqlalchemy import and_
from flask_login import login_required, current_user
from flask import Flask, render_template, redirect, flash, Blueprint, request, jsonify, url_for
from ParkingLotServer import app, db
from .models import ParkingLot, Utilization, Charge


mod_admin = Blueprint('admin', __name__)


@mod_admin.route('/viewUpdatePrices', methods=['GET', 'POST'])
@login_required
def view_update_prices():
    # Getting Parking Lot List from the DB through model and sending it to utilization page
    days = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"]
    hoursList = ["D \ H", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"]
    plList = []
    plListMap, plIdToNameMap = {}, {}
    plListRaw = ParkingLot.query.filter_by(pl_active='t').all()
    for plListRawItem in plListRaw:
        plList.append(plListRawItem.pl_name)
        plListMap[plListRawItem.pl_name] = plListRawItem.id
        plIdToNameMap[plListRawItem.id] = plListRawItem.pl_name

    headerTitle = 'Parking Lot - Price Snapshot'
    if request.method == 'POST':

        parking_lot_id = request.form.get("parking_lot_id")
        price_snapshot = request.form.get("price_snapshot")

        # Reset the old active price_snapshot for that parkinglot
        old_active_charges = Charge.query.filter(and_(Charge.pl_id == parking_lot_id, Charge.ch_active == True)).update({Charge.ch_active: False})
        # Update the new received price
        new_charge = Charge(parking_lot_id, price_snapshot, True)
        db.session.add(new_charge)
        db.session.commit()

        return jsonify({
            'message': 'ok'
            })

    if request.method == 'GET':
        #if request.form['button'] == 'view_pricesnapshot':
        selected_pl = request.args.get('pl')
        #selected_pl = request.form['inputPLSelect']

        # Check if parking lot is present
        if selected_pl not in plListMap:
            return render_template('viewprices.html',
                                    headerTitle=headerTitle,
                                    parkinglotList=plList,
                                    daysList=days,
                                    hoursList=hoursList,
                                    priceDataPresent=False)

        parklot_id = plListMap[selected_pl]
        charge_obj = Charge.query.filter_by(pl_id=parklot_id, ch_active='t').first()
        if not charge_obj:
            return render_template('viewprices.html',
                                    headerTitle=headerTitle,
                                    parkinglotList=plList,
                                    daysList=days,
                                    hoursList=hoursList,
                                    priceDataPresent=False,
                                    spl=plIdToNameMap[parklot_id],
                                    message="No charge data available")

        # Convert to lists
        price_snapshot = charge_obj.price_snapshot.split("#")
        for i, day in enumerate(price_snapshot):
            price_snapshot[i] = price_snapshot[i].split(",")

        return render_template('viewprices.html',
                                headerTitle=headerTitle,
                                parkinglotList=plList,
                                priceDataPresent='true',
                                parkinglotname=selected_pl,
                                daysList=days,
                                hoursList=hoursList,
                                parking_lot_id=parklot_id,
                                spl=plIdToNameMap[parklot_id],
                                pricesnapshot=price_snapshot)

    return render_template('viewprices.html', headerTitle=headerTitle, parkinglotList=plList, daysList=days, hoursList=hoursList,
                            parking_lot_id=parklot_id,priceDataPresent=True)


def get_parking_lots():
    plList = []
    plListMap = {}
    plListRaw = ParkingLot.query.filter_by(pl_active='t').all()
    for plListRawItem in plListRaw:
        plList.append([plListRawItem.pl_name, plListRawItem.pl_address, plListRawItem.pl_capacity, plListRawItem.pl_default_price, plListRawItem.id])
        plListMap[str(plListRawItem.id)] = plListRawItem
    return plList, plListMap


@mod_admin.route('/configureParkingLots', methods=['GET', 'POST'])
@login_required
def configure_parking_lots():
    plList, plListMap = get_parking_lots()
    if request.method == 'POST':
        #Parking lot addition operation
        if request.form['button'] == 'add_pl':
            parking_lot = ParkingLot(request.form['pl_name'], request.form['pl_address'], request.form['pl_capacity'], request.form['pl_price'], True)
            db.session.add(parking_lot)
            db.session.commit()

            # Insert default price snapshot
            default_price = request.form['pl_price'].strip()
            default_price_snapshot = "#".join([",".join([default_price] * 24)] * 7)
            default_charge = Charge(parking_lot.id, default_price_snapshot, True)
            db.session.add(default_charge)
            db.session.commit()

            # if parking_lot.id != 1 :
            #     flash('Error in adding parking lot')
    plList, plListMap = get_parking_lots()
    return render_template('parkinglots.html', headerTitle='Parking Lot - Configuration', parkinglotList=plList)


@mod_admin.route('/utilization', methods=['GET', 'POST'])
@login_required
def view_utilization():
    # Getting Parking Lot List from the DB through model and sending it to utilization page
    plList = []
    plListMap = {}
    plListRaw = ParkingLot.query.filter_by(pl_active='t').all()
    for plListRawItem in plListRaw:
        plList.append(plListRawItem.pl_name)
        plListMap[plListRawItem.pl_name] = plListRawItem.id

    if request.method == 'POST':
        if request.form['button'] == 'view_utilization':
            selected_date = request.form['inputDateSelect']
            selected_pl = request.form['inputPLSelect']
            parklot_id = plListMap[selected_pl]

            selected_date_day = selected_date[selected_date.rfind('-') + 1:]
            selected_date_month = selected_date[selected_date.find('-') + 1:selected_date.rfind('-')]
            selected_date_year = selected_date[0:selected_date.find('-')]
            selDate = datetime.date(int(selected_date_year), int(selected_date_month), int(selected_date_day))

            selDateM1 = selDate - datetime.timedelta(days=1)
            selDateM2 = selDate - datetime.timedelta(days=2)
            
            print str(selected_date_day) + ' ' + str(selected_date_month) + ' ' + str(selected_date_year)
            
            selDateStats = Utilization.query.filter(and_(Utilization.pl_id == parklot_id, Utilization.util_date == str(selDate))).first()
            
            #When no data for the date selected is found then error message is displayed
            if(selDateStats is None):
                return render_template('utilization.html',
                                       headerTitle='Parking Lot - Utilization',                                  parkinglotList = plList,
                                       chartDataPresent = 'no',
                                       sdate = selected_date,
                                       spl = selected_pl)
            selDateM1Stats = Utilization.query.filter(and_(Utilization.pl_id == parklot_id, Utilization.util_date == str(selDateM1))).first()
            
            selDateM2Stats = Utilization.query.filter(and_(Utilization.pl_id == parklot_id, Utilization.util_date == str(selDateM2))).first()

            #When no data for the previous day to date selected is found but data for previous to previous day is present
            if(selDateM1Stats is None and selDateM2Stats is not None):
                return render_template('utilization.html',
                                        headerTitle='Parking Lot - Utilization',
                                        parkinglotList=plList,
                                        chartDataPresent='yes',
                                        sdate=selected_date,
                                        sdate_year=selected_date_year,
                                        sdate_month=selected_date_month,
                                        sdate_day=selected_date_day,
                                        spl=selected_pl,
                                        perHourUtil=selDateStats.util_per_hour,
                                        perHourRev=selDateStats.rev_per_hour    ,
                                        selDateUtil=selDateStats.avg_util,
                                        selDateRev=selDateStats.total_rev,
                                        selDateM1Util=0.0,
                                        selDateM1Rev=0.0,
                                        selDateM2Util=selDateM2Stats.avg_util,
                                        selDateM2Rev=selDateM2Stats.total_rev)
            
            #When no data for the previous to previous day to date selected is found but data for previous day is present
            elif(selDateM1Stats is not None and selDateM2Stats is None):
                return render_template('utilization.html',
                                        headerTitle='Parking Lot - Utilization',
                                        parkinglotList=plList,
                                        chartDataPresent='yes',
                                        sdate=selected_date,
                                        sdate_year=selected_date_year,
                                        sdate_month=selected_date_month,
                                        sdate_day=selected_date_day,
                                        spl=selected_pl,

ParkingLotServer_APP/ParkingLotServer/authentication/controllers.py
import arrow
import jwt
from passlib.hash import argon2
from flask import url_for, render_template, redirect, flash, g, Blueprint, request, jsonify
from flask_login import logout_user, login_user, current_user, login_required
from ParkingLotServer import app, db
from .models import Users

mod_auth = Blueprint('authentication', __name__)


@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    errorMsg = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = Users.query.filter_by(email=email).first()
        if user is not None and user.authenticate(password):
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash('Thanks for logging in, {}'.format(current_user.email))
            return redirect(url_for('admin.show_dashboard', headerTitle='Parking Lot Administration - Dashboard'))
        else:
            errorMsg = 'Invalid Login! Try Again.'
    return render_template('login.html', headerTitle='Parking Lot Administration - Login', errorMessage=errorMsg)


@mod_auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html', headerTitle='Parking Lot Administration - Register')
    user = Users(request.form['firstname'], request.form['lastname'], request.form['email'], request.form['password'])
    db.session.add(user)
    db.session.commit()
    flash('User successfully registered')
    return redirect(url_for('authentication.login', headerTitle='Parking Lot Administration - Login'))


@mod_auth.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('authentication.login'))


@mod_auth.route('/change_password', methods=['POST'])
@login_required
def change_password():
    old_password = request.form['old_password']
    new_password = request.form['new_password']
    if current_user.change_password(old_password, new_password):
        flash('Password changed successfully', 'info')
        return redirect(url_for('authentication.login', headerTitle='Parking Lot Administration - Login'))
    else:
        flash('Some error occured', 'error')
        return redirect(url_for('authentication.change_password', headerTitle='Parking Lot Administration - Change Password'))

ParkingLotServer_APP/ParkingLotServer/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>Parking Lot Administration</title>
	<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="{{url_for('static', filename='new.css')}}" rel="stylesheet">
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</head>
	<style>

		table {
		    font-family: arial, sans-serif;
		    border-collapse: collapse;
		    width: 100%;
		}

		td, th {
		    border: 1px solid #dddddd;
		    text-align: left;
		    padding: 8px;
		}

		tr:nth-child(even) {
		    background-color: #dddddd;
		}

	</style>

	<body>
	<div class="container">
      <div style="padding-top:0.5em">
        <h1>{{headerTitle}}</h1>
      </div>

      <div class="jumbotron">
		{% block content %}
        {% endblock %}
      </div>

      <footer class="footer">
        <p>&copy; Team-3 2018</p>
      </footer>

    </div>
  </body>
</html>

ParkingLotServer_APP/ParkingLotServer/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
  <form>
    <div style="margin-bottom:20px">
        <h2>Welcome, {{username}}</h2>
    </div>
    
	<!--<div style="margin-bottom:20px">
	<a class="btn btn-primary btn-block" href="{{url_for('admin.configure_parking_lots')}}">Add Parking Lots</a>
	<a class="btn btn-primary btn-block" href="{{url_for('admin.view_utilization')}}">View Utilization</a>
	<a class="btn btn-primary btn-block" href="{{url_for('admin.view_update_prices')}}">View / Update Prices</a>
	<a class="btn btn-primary btn-block" href="{{url_for('authentication.logout')}}">Log Out</a>
	</div>-->
    
    <div style="margin-bottom:20px">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('admin.configure_parking_lots')}}">Add Parking Lots</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('admin.view_utilization')}}">View Utilization</a>
				</li>
                <li class="nav-item active">
					<a class="nav-link" href="{{url_for('admin.view_update_prices')}}">View / Update Prices</a>
				</li>
                <li class="nav-item">
					<a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
				</li>
			</ul>
		</div>
	</nav>
	</div>
    
    <div id="dashplot" style="margin-bottom:20px"><!-- Plotly chart will be drawn inside this DIV --></div>
	<script>
		var trace1 = {
			x: ['Parking Lot 1', 'Parking Lot 2', 'Parking Lot 3', 'Parking Lot 4'],
			y: [75, 80, 65, 90],
			name: 'Average Utilization',
			type: 'bar'
		};

		var trace2 = {
			x: ['Parking Lot 1', 'Parking Lot 2', 'Parking Lot 3', 'Parking Lot 4'],
			y: [50000, 60000, 50000, 65000],
			name: 'Total Revenue',
			yaxis: 'y2',
			type: 'line'
		};

		var data = [trace1, trace2];

		var layout = {
			//barmode: 'group',
			//width: 500,
			height: 300,
			title: 'Overall Average Utilization and Total Revenue', 
			yaxis: {title: 'Average Utilization',
			titlefont: {color: 'rgb(31, 120, 180)'}, 
			tickfont: {color: 'rgb(31, 120, 180)'},
			}, 
			yaxis2: {
			title: 'Total Revenue',
			titlefont: {color: 'rgb(255, 126, 11)'},
			tickfont: {color: 'rgb(255, 126, 11)'}, 
			overlaying: 'y', 
			side: 'right'
			},
			showlegend:false
		};

		Plotly.newPlot('dashplot', data, layout);
	</script>
    
    <div id="dashplot2" style="margin-bottom:20px"><!-- Plotly chart will be drawn inside this DIV --></div>
	<script>
		var trace1 = {
          x: ['Parking Lot 1 - Operator 1', 'Parking Lot 2 - Operator 2', 'Parking Lot 3 - Operator 2', 'Parking Lot 4 - Operator 1'],
          y: [200, 140, 230, 170],
          name: 'Entry Transactions',
          type: 'bar'
        };

        var trace2 = {
          x: ['Parking Lot 1 - Operator 1', 'Parking Lot 2 - Operator 2', 'Parking Lot 3 - Operator 2', 'Parking Lot 4 - Operator 1'],
          y: [250, 100, 200, 180],
          name: 'Exit Transactions',
          type: 'bar'
        };

        var data = [trace1, trace2];

        var layout = {
            height: 300,
            barmode: 'group',
            title: 'Top performing operators - Monthly'};

		Plotly.newPlot('dashplot2', data, layout);
	</script>
  </form>
{% endblock %}

ParkingLotServer_APP/ParkingLotServer/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form action="" method=post>
	{% if errorMessage %}
	<div class="alert alert-danger" role="alert">
		{{errorMessage}}
	</div>
	{% endif %}
    <h2> Sign in </h2>
    <div class="form-group">
	  <input type="text" id="email" name="email" class="form-control"
		placeholder="Enter email" required> <br />
	  <input type="password" id="password" name="password" class="form-control"
		placeholder="Enter password" required> <br />
	  <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </form>
{% endblock %}

ParkingLotServer_APP/ParkingLotServer/templates/parkinglots.html
{% extends "base.html" %}
{% block content %}
	<div style="margin-bottom:20px">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('admin.show_dashboard')}}">Dashboard</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
				</li>
			</ul>
		</div>
	</nav>
	</div>  
	<div class="container">
	  <div id="table" class="table-editable">
	    <table id="parkinglots" class="table" align="center">
	      <tr>
		<th>Name</th>
		<th>Address</th>
		<th>Capacity</th>
		<th>Price</th>
	      </tr>
		{% for item in parkinglotList %}
		
	   	<tr>
		<!--<td contenteditable="false">{{item[0]}}</td>
		<td contenteditable="true">{{item[1]}}</td>
		<td contenteditable="true">{{item[2]}}</td>
		<td contenteditable="true">{{item[3]}}</td>-->
		

		<form method=post>
		<td>{{item[0]}}</td>
		<td>{{item[1]}}</td>
		<td>{{item[2]}}</td>
		<td>{{item[3]}}</td>
		<input type="hidden" name="id" value="{{item[4]}}"></input>

		<!--<td>
		  <button name="button" class="btn btn-primary btn-block" type="submit" value="delete_pl">Delete</button>
		</td>-->
		</form>		      	
		</tr>
		{% endfor %}
		
	    </table>
	  </div>
	  
      <div class="input-group" style="margin-bottom:20px">
		<button id="add" class="btn btn-primary btn-block">Add Parking Lot</button>
	  </div>
	</div>
	

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
	    $('#add').click(function() {
	       $('#table').append('<form method=post name="add_form"><table class="table"> <tr><td><input name="pl_name" placeholder="Name" type="text" data-validation="required"></input> </td><td><input name="pl_address" placeholder="Address" type="text" data-validation="required"></input></td><td><input name="pl_capacity" placeholder="Capacity" type="text" data-validation="number"></input></td>	<td><input name="pl_price" placeholder="Price" type="text" data-validation="number" data-validation-allowing="range[1;100]"></input></td><td><button name="button" class="btn btn-primary btn-block" type="submit" value="add_pl">Add</button></td></tr></table></form>');
	    });
	});
	</script>
	<script>
	
	$.validate({
  		form : '#add_form'
	});
	</script>
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
	<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js'></script>
	<script src='https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js'></script>
	<script src='http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore.js'></script>

	  

	<!--<script src="js/index.js"></script>-->
	

{% endblock %}

ParkingLotServer_APP/ParkingLotServer/templates/register.html
{% extends "base.html" %}
{% block content %}
  <form action="" method=post>
    <h2> Register </h2>
    <div class="form-group">
        <input type="text" id="firstname" name="firstname" class="form-control"
            placeholder="Enter FirstName" value="{{ request.form.firstname }}" required>
        <br />   
        <input type="text" id="lastname" name="lastname" class="form-control"
            placeholder="Enter LastName" value="{{ request.form.lastname }}"
            required>
        <br />   
        <input type="email" id="email" name="email" class="form-control"
            placeholder="Enter Email" value="{{ request.form.email }}"
            required>
        <br />
        <input type="password" id="password" name="password" class="form-control"
            placeholder="Enter Password" value="{{ request.form.password }}"
            required>
        <br />
        <button type="submit" class="btn btn-primary">Signup</button>
    </div>
  </form>
{% endblock %}

ParkingLotServer_APP/ParkingLotServer/templates/utilization.html
{% extends "base.html" %}
{% block content %}
<form method=post>
	<div style="margin-bottom:20px">
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{{url_for('admin.show_dashboard')}}">Dashboard</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
				</li>
			</ul>
		</div>
	</nav>
	</div>
	<h5>View utilization statistics for: </h5>
	<div class="input-group" style="margin-bottom:20px">
		<div class="input-group-prepend">
			<label class="input-group-text" for="inputPLSelect">Parking Lot</label>
		</div>
		<select class="custom-select" name="inputPLSelect" required>
		{% for item in parkinglotList %}
			{% if item == spl %}
				<option selected>{{item}}</option>
			{% else %}
				<option>{{item}}</option>
			{% endif %}
		{% endfor %}
		</select>     
	</div>
	
	<div class="input-group" style="margin-bottom:20px">
		<div class="input-group-prepend">
			<label class="input-group-text" for="inputDateSelect">Date<span style="display:inline-block; width:48px;"></span></label>
		</div>
		<input class="form-control" type="date" name="inputDateSelect" value="{{sdate}}" required/>
	</div>

	<div class="input-group" style="margin-bottom:20px">
		<button name="button" class="btn btn-primary btn-block" type="submit" value="view_utilization">View Utilization</button>
	</div>
	
	{% if chartDataPresent == 'yes' %}
	<div class="clearfix">
	<div id="box1" style="float:left; margin-bottom:20px"><!-- Plotly chart will be drawn inside this DIV --></div>
	<script>
		var trace1 = {
		  x: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
		  y: {{perHourUtil}},
		  name: 'Utilization', 
		  type: 'scatter'
		};

		var trace2 = {
		  x: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
		  y: {{perHourRev}},
		  name: 'Revenue', 
		  yaxis: 'y2', 
		  type: 'scatter'
		};

		var data = [trace1, trace2];

		var layout = {
		  width: 500,
		  height: 300,
		  title: 'Hourly Utilization and Revenue', 
		  yaxis: {title: 'Utilization',
			titlefont: {color: 'rgb(31, 120, 180)'}, 
			tickfont: {color: 'rgb(31, 120, 180)'},
		  }, 
		  yaxis2: {
			title: 'Revenue', 
			titlefont: {color: 'rgb(255, 126, 11)'}, 
			tickfont: {color: 'rgb(255, 126, 11)'}, 
			overlaying: 'y', 
			side: 'right'
		  },
		  showlegend:false
		};

		Plotly.newPlot('box1', data, layout);
	</script>
	
	<div id="box2" style="float:right; margin-bottom:20px"><!-- Plotly chart will be drawn inside this DIV --></div>
	<script>
		var d = new Date();
		d.setDate({{sdate_day}});
		d.setMonth({{sdate_month}}-1);
		d.setFullYear({{sdate_year}});
		var dm1 = new Date(d);
		dm1.setDate(d.getDate() - 1);
		var dm2 = new Date(d);
		dm2.setDate(d.getDate() - 2);
		var dStr = d.getDate() + '/' + (d.getMonth()+1) + '/' + d.getFullYear();
		var dm1Str = dm1.getDate() + '/' + (dm1.getMonth()+1) + '/' + dm1.getFullYear();
		var dm2Str = dm2.getDate() + '/' + (dm2.getMonth()+1) + '/' + dm2.getFullYear();
		
		var trace1 = {
			x: [dm2Str, dm1Str, dStr],
			y: [{{selDateM2Util}}, {{selDateM1Util}}, {{selDateUtil}}],
			name: 'Utilization',
			type: 'bar'
		};

		var trace2 = {
			x: [dm2Str, dm1Str, dStr],
			y: [{{selDateM2Rev}}, {{selDateM1Rev}}, {{selDateRev}}],
			name: 'Revenue',
			yaxis: 'y2',
			type: 'line'
		};

		var data = [trace1, trace2];

		var layout = {
			//barmode: 'group',
			width: 500,
			height: 300,
			title: 'Average Utilization and Revenue (Past Days)', 
			yaxis: {title: 'Utilization',
			titlefont: {color: 'rgb(31, 120, 180)'}, 
			tickfont: {color: 'rgb(31, 120, 180)'},
			}, 
			yaxis2: {
			title: 'Revenue',
			titlefont: {color: 'rgb(255, 126, 11)'},
			tickfont: {color: 'rgb(255, 126, 11)'}, 
			overlaying: 'y', 
			side: 'right'
			},
			showlegend:false
		};

		Plotly.newPlot('box2', data, layout);
	</script>
	</div>
    {% elif chartDataPresent == 'no' %}
    <div class="alert alert-danger" style="margin-bottom:20px"><p>No data present for the selected parking lot and date</p></div>
    {% endif %}
  </form>
{% endblock %}