ParkingLotClient_APP/ParkingLotClient/authentication/controllers.py
from flask import url_for, render_template, redirect, flash, g, Blueprint, request, jsonify
from flask_login import login_required, logout_user, login_user, current_user
from ParkingLotClient import app, db
from .models import Users


mod_auth = Blueprint('authentication', __name__)


@mod_auth.route('/login', methods=['GET','POST'])
def login():
    errorMsg = ''
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = Users.query.filter_by(email=email).first()
        if user is not None and user.authenticate(password):
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            login_user(user)
            flash('Thanks for logging in, {}'.format(current_user.email))
            return redirect(url_for('client.show_home', headerTitle='Parking Lot System - Dashboard'))
        else:
            errorMsg = 'Invalid Login! Try Again.'
    return render_template('login.html', headerTitle='Parking Lot System - Login', errorMessage=errorMsg)


@mod_auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    user = Users(request.form['firstname'], request.form['lastname'], request.form['email'], request.form['password'])
    db.session.add(user)
    db.session.commit()
    flash('User successfully registered')
    return redirect(url_for('authentication.login'))


@mod_auth.route('/logout')
@login_required
def logout():
    user = current_user
    user.authenticated = False
    db.session.add(user)
    db.session.commit()
    logout_user()
    flash('Goodbye!', 'info')
    return redirect(url_for('authentication.login'))


@mod_auth.route('/change_password', methods=['POST'])
@login_required
def change_password():
    old_password = request.form['old_password']
    new_password = request.form['new_password']
    if current_user.change_password(old_password, new_password):
        flash('Password changed successfully', 'info')
        return redirect(url_for('authentication.login'))
    else:
        flash('Some error occured', 'error')
        return redirect(url_for('authentication.change_password'))

ParkingLotClient_APP/ParkingLotClient/client/controllers.py
from sqlalchemy import and_, func, between
from flask_login import login_required, current_user
from flask import Flask, render_template, redirect, url_for, session, g, Blueprint, request, jsonify, url_for

import datetime
from datetime import datetime as dt
from datetime import timedelta

from ParkingLotClient import db, app, socketio
from .models import Token, Charge, ParkingLot, HourlyUtil

mod_client = Blueprint('client', __name__)


def populateHourlyUtil():
    try:
        # Getting current date and current hour
        currDT = str(dt.now())
        currDate = currDT[0:currDT.find(' ')]
        currHour = currDT[currDT.find(' '):currDT.find(':')].strip()
        currHourInt = int(currHour)

        # Getting capacity of the current parking lot
        activePL = ParkingLot.query.filter_by(pl_active='t').first()
        parkingLotCapacity = int(activePL.pl_capacity)

        # Getting number of current occupied slots and utilization percentage
        currActiveTokens = Token.query.filter_by(exit_date=None).all()
        currUtil = parkingLotCapacity - len(currActiveTokens)
        currUtilPercent = (currUtil * 100) / parkingLotCapacity

        if(currHourInt == 0):
            prevDT = str(dt.now() - timedelta(days=1))
            prevDate = prevDT[0:prevDT.find(' ')]

            # Getting exit transactions of the last hour of the previous day
            lastHourTransactions = Token.query.filter(between(Token.exit_date, func.to_date(prevDate + " 23:00", "YYYY-MM-DD HH24:MI"), func.to_date(prevDate + " 23:59", "YYYY-MM-DD HH24:MI"))).all()

            # Getting revenue collected till start of the last hour
            prevRev = 0.0

            lastlastHourUtil = HourlyUtil.query.filter(and_(HourlyUtil.util_date == func.to_date(prevDate, "YYYY-MM-DD"), HourlyUtil.util_hour == 22)).first()
            if(lastlastHourUtil is None):
                prevRev = 0.0
            else:
                prevRev = float(lastlastHourUtil.rev)

            # Getting revenue collected in the last hour
            currRev = 0.0
            for lastHourTransaction in lastHourTransactions:
                currRev = currRev + float(lastHourTransaction.computed_charge)

            # Computing cumulative revenue and storing as a new row in the Hourly Util table
            currCumuRev = currRev + prevRev
            hourlyUtilEntry = HourlyUtil(prevDate, 23, currUtilPercent, currCumuRev)
            db.session.add(hourlyUtilEntry)
            db.session.commit()
        else:

            # Getting exit transactions of the last hour
            lastHourTransactions = Token.query.filter(between(Token.exit_date, func.to_date(currDate + " " + str(currHourInt - 1) + ":00", "YYYY-MM-DD HH24:MI"), func.to_date(currDate + " " + str(currHourInt - 1) + ":59", "YYYY-MM-DD HH24:MI"))).all()

            # Getting revenue collected till start of the last hour
            prevRev = 0.0
            if(currHourInt >= 2):
                lastlastHourUtil = HourlyUtil.query.filter(and_(HourlyUtil.util_date == func.to_date(currDate, "YYYY-MM-DD"), HourlyUtil.util_hour == (currHourInt - 2))).first()
                if(lastlastHourUtil is None):
                    prevRev = 0.0
                else:
                    prevRev = float(lastlastHourUtil.rev)

            # Getting revenue collected in the last hour
            currRev = 0.0
            for lastHourTransaction in lastHourTransactions:
                currRev = currRev + float(lastHourTransaction.computed_charge)

            # Computing cumulative revenue and storing as a new row in the Hourly Util table
            currCumuRev = currRev + prevRev
            hourlyUtilEntry = HourlyUtil(currDate, currHour, currUtilPercent, currCumuRev)
            db.session.add(hourlyUtilEntry)
            db.session.commit()

    except Exception, e:
        print e


def getCurUtilization():
    activePL = ParkingLot.query.filter_by(pl_active='t').first()
    parkingLotCapacity = int(activePL.pl_capacity)

    # Getting number of current occupied slots and utilization percentage
    currActiveTokens = Token.query.filter_by(exit_date=None).all()
    emptySlots = parkingLotCapacity - len(currActiveTokens)
    return parkingLotCapacity, emptySlots


def computerAvgParkingLotRate():
        activeCharge = Charge.query.filter(Charge.ch_active.is_(True)).first()
        if (activeCharge is not None):
            price_snapshot = activeCharge.price_snapshot
        else:
            inactiveCharge = Charge.query.filter(Charge.ch_active.is_(False)).first()
            if (inactiveCharge is not None):
                price_snapshot = inactiveCharge.price_snapshot
        ls = price_snapshot.split('#')
        snap = []
        for i in ls:
            snap.append(i.split(','))

        now = dt.now()
        now_day = now.weekday()
        now_day = (now_day + 1) % 7
        now_hour = now.hour

        summ = 0
        four_hour_avg = 0
        one_day_avg = 0
        two_day_avg = 0

        for i in range(now_hour, now_hour + 4):
            four_hour_avg += float(snap[now_day][i % 24])
        four_hour_avg = float(four_hour_avg) / 4

        # calculate average for one day
        for i in range(0, 24):
            summ += float(snap[now_day][i])
        one_day_avg = float(summ) / 24

        # calculate average for more than one day
        j = 1
        while j != 2:
            now_day = (now_day + 1) % 7
            for i in range(0, 24):
                summ += float(snap[now_day][i])
            j = j + 1

        two_day_avg = float(summ) / (24 * 2)
        return int(four_hour_avg), int(one_day_avg), int(two_day_avg)


@mod_client.route('/home', methods=['GET', 'POST'])
@login_required
def show_home():
    return render_template('home.html', headerTitle='Parking Lot - Home', username=current_user.first_name + " " + current_user.last_name)


@mod_client.route('/ParkingLotDisplay', methods=['GET', 'POST'])
def display_info():
    four_hour_avg, one_day_avg, two_day_avg = computerAvgParkingLotRate()
    totalSlots, emptySlots = getCurUtilization()

    return render_template('ParkingLotDisplay.html', headerTitle='Parking Lot - Info', pl_total_slots=totalSlots, pl_empty_slots=emptySlots, fourHourAvg=int(four_hour_avg), oneDayAvg=int(one_day_avg), twoDayAvg=int(two_day_avg))


@mod_client.route('/print_summary', methods=['GET', 'POST'])
@login_required
def print_summary():

    if(session['allow']):

        pay_method = session['pay_method']
        session['pay_method'] = ""

        final_price = session['final_price']
        session['final_price'] = ""

        token_id = session['token_id']
        session['token_id'] = ""

        exit_time = session['exit_time']
        session['exit_time'] = ""

        session['allow'] = False

        return render_template('summary.html', headerTitle='Parking Lot - Receipt for Customer', pay_method=pay_method, final_price=final_price, token_id=token_id, exit_time=exit_time)


def calc_for_date(start_dtime, end_dtime, snap):
    temp_sum = 0
    weekday = start_dtime.weekday()
    weekday = (weekday + 1) % 7
    entry_hour = start_dtime.hour
    exit_hour = end_dtime.hour

    for i in range(entry_hour, exit_hour + 1):
        temp_sum += float(snap[weekday][i])

    return temp_sum


def calc_price(entry_dtime, exit_dtime, price_snapshot):

    # Converting the string snapshot into suitable list of lists structure
    ls = price_snapshot.split('#')
    price_snapshot = []
    for i in ls:
        price_snapshot.append(i.split(','))

    ls = []
    summ = 0

    days = (exit_dtime.date() - entry_dtime.date()).days
    fin_time = dt.strptime("23:59:00", '%H:%M:%S')
    start_time = dt.strptime("00:01:00", '%H:%M:%S')
    fin_time = fin_time.time()
    start_time = start_time.time()

    # If car entered and exited on the same Date
    if(days == 0):
        summ = calc_for_date(entry_dtime, exit_dtime, price_snapshot)

    # If car entered and exited on different dates
    else:

        for i in range(days + 1):

            if i == 0:
                summ += calc_for_date(entry_dtime, dt.combine(entry_dtime.date(), fin_time), price_snapshot)
            if i > 0 and i < days:
                temp_date = entry_dtime.date() + datetime.timedelta(days=i)
                summ += calc_for_date(dt.combine(temp_date, start_time), dt.combine(temp_date, fin_time), price_snapshot)

            if i == days:
                summ += calc_for_date(dt.combine(exit_dtime.date(), start_time), exit_dtime, price_snapshot)

    return summ


def pay():
    return True


@mod_client.route('/exit', methods=['GET', 'POST'])
@login_required
def exit_processing():

    if request.method == 'POST':

        token_input = request.form["token_id"]
        pay_method = request.form["pay_method"]
        token_object_exists = 0

        # Extract Token corresponding to queried token_id
        if token_input.isdigit():
            token_object_exists = Token.query.filter_by(token_id=token_input).count()
            token_object = Token.query.filter_by(token_id=token_input).first()

        if token_object_exists > 0:
            if token_object.exit_date is None:

                exit_dtime = dt.now()
                entry_dtime = token_object.entry_date
                exit_dtime = dt.strptime(exit_dtime.strftime('%Y-%m-%d %H:%M'), '%Y-%m-%d %H:%M')

                # Extract Charge corresponding to the Particular token
                charge_object = Charge.query.filter_by(charge_id=token_object.charge_id).first()
                price_snapshot = charge_object.price_snapshot

                # Find the amount Customer needs to pay
                final_price = calc_price(entry_dtime, exit_dtime, price_snapshot)
                final_price = float("{0:.2f}".format(final_price))

                # Customer pays the amount
                if not pay():
                    return render_template('exit.html', headerTitle='Parking Lot - Exit', errorMsg="Payment Failed")

ParkingLotClient_APP/ParkingLotClient/templates/ParkingLotDisplay.html
{% extends "base.html" %}
{% block content %}

<body>

  <form>
  <div>

  <div class="line"></div>

    <table border="2" cellpadding="3" cellspacing="1" align="center">
      <tr>
        <td style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span>Total Capacity</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span id="total_slots">{{pl_total_slots}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span>Empty Slots</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span id="empty_slot">{{pl_empty_slots}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span>Current Average Price</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span id="hourlyavgprice">{{fourHourAvg}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span>Daily Average Price</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span id="dailyavgprice">{{oneDayAvg}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span>Weekly Average Price</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:72px; padding-left:20px; padding-right:20px">
            <span id="weeklyavgprice">{{twoDayAvg}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
    </table>

  </div>
  </form>

  <script type="text/javascript" charset="utf-8">
    var socket = io.connect();
    // verify our websocket connection is established
    socket.on('connect', function() {
          console.log("connected");
    });

    socket.on('PL_Message', function(data) {
          console.log(data);
          document.getElementById("empty_slot").innerHTML = data.pl_empty_slots;
    });

    socket.on('Charge_Message', function(data) {
          console.log(data);
          document.getElementById("hourlyavgprice").innerHTML = data.fourHourAvg;
          document.getElementById("dailyavgprice").innerHTML = data.oneDayAvg;
          document.getElementById("weeklyavgprice").innerHTML = data.twoDayAvg;
    });

  </script>

</body>

{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
	<title>Parking Lot System</title>
	<link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="{{url_for('static', filename='new.css')}}" rel="stylesheet">
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	</head>

	<body>
	<div class="container">
      <div style="padding-top:0.5em">
        <h1>{{headerTitle}}</h1>
      </div>

      <div class="jumbotron">
		{% block content %}
        {% endblock %}
      </div>

      <footer class="footer">
        <p>&copy; Team-3 2018</p>
      </footer>

    </div>
  </body>
</html>

ParkingLotClient_APP/ParkingLotClient/templates/entry.html
{% extends "base.html" %}
{% block content %}


<div style="margin-bottom:20px">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
	  <a class="nav-link" href="{{url_for('client.show_home')}}">Home</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
	</li>
      </ul>
    </div>
  </nav>
</div>

<form action ="{{ url_for('client.entry_processing') }}" method = "post">

{% if errorMessage %}
	<div class="alert alert-danger" role="alert">
		{{errorMessage}}
	</div>
{% endif %}

  Car Number:<br/>
  <input type="text" name="CarNumber" style="margin-bottom:20px">
  <br/>

  <input type="submit">

</form>

{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/exit.html
{% extends "base.html" %}
{% block content %}

<body>


<div style="margin-bottom:20px">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
	  <a class="nav-link" href="{{url_for('client.show_home')}}">Home</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
	</li>
      </ul>
    </div>
  </nav>
</div>


{% if errorMsg %}

<div class="alert alert-danger" role="alert">
  {{errorMsg}}
</div>
{% endif %}


<form action ="{{ url_for('client.exit_processing') }}" method = "post">

  Input Token Id:<br/>
  <input type="text" name="token_id" style="margin-bottom:20px">
  <br/>

  Input Payment Method:<br/>
  <select class="custom-select" name="pay_method" required>
    <option value = "Cash">Cash</option>
    <option value = "Online">Online</option>
  </select>
  <br/>
  <br/>
  <div class="input-group" style="margin-bottom:20px">
    <button name="button" class="btn btn-primary btn-block" type="submit">Submit</button>
  </div>


</form>
</body>
{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/home.html
{% extends "base.html" %}
{% block content %}
  <form>
    <div style="margin-bottom:20px">
        <h2>Welcome, {{username}}</h2>
    </div>
    
	<div>
    <a class="btn btn-primary btn-block" href="{{url_for('client.entry_processing')}}">Entry</a>
	<a class="btn btn-primary btn-block" href="{{url_for('client.exit_processing')}}">Exit</a>
	<a class="btn btn-primary btn-block" href="{{url_for('authentication.logout')}}">Logout</a>
	</div>
  </form>
{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form action="" method=post>
	{% if errorMessage %}
	<div class="alert alert-danger" role="alert">
		{{errorMessage}}
	</div>
	{% endif %}
    <h2> Sign in </h2>
    <div class="form-group">
	  <input type="text" id="email" name="email" class="form-control"
		placeholder="Enter email" required> <br />
	  <input type="password" id="password" name="password" class="form-control"
		placeholder="Enter password" required> <br />
	  <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </form>
{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/payment.html
{% extends "base.html" %}
{% block content %}


<div style="margin-bottom:20px">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
	  <a class="nav-link" href="{{url_for('client.show_home')}}">Home</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
	</li>
      </ul>
    </div>
  </nav>
</div>

<div>

<div class="line"></div>
    <div style="text-align: center;">
        <span style="font-size:24px;">Payment Successful</span>
    </div>
    
    <table border="2" cellpadding="3" cellspacing="1" align="center">
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Token ID</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{token_id}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Amount</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{final_price}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Paid by</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{pay_method}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Exit Time</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{exit_time}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
    </table>

    <div class="input-group" style="margin-bottom:20px">
        <a class="nav-link" style="width:100%" href="{{url_for('client.show_home')}}">
          <button name="button" class="btn btn-primary btn-block">Print</button>
        </a>
    </div>


  </div>

{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/register.html
{% extends "base.html" %}
{% block content %}
  <form action="" method=post>
    <h2> Register </h2>
    <div class="form-group">
        <input type="text" id="firstname" name="firstname" class="form-control"
            placeholder="Enter FirstName" value="{{ request.form.firstname }}" required>
        <br />   
        <input type="text" id="lastname" name="lastname" class="form-control"
            placeholder="Enter LastName" value="{{ request.form.lastname }}"
            required>
        <br />   
        <input type="email" id="email" name="email" class="form-control"
            placeholder="Enter Email" value="{{ request.form.email }}"
            required>
        <br />
        <input type="password" id="password" name="password" class="form-control"
            placeholder="Enter Password" value="{{ request.form.password }}"
            required>
        <br />
        <button type="submit" class="btn btn-primary">Signup</button>
    </div>
  </form>
{% endblock %}

ParkingLotClient_APP/ParkingLotClient/templates/summary.html
{% extends "base.html" %}
{% block content %}


<div style="margin-bottom:20px">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
	<li class="nav-item active">
	  <a class="nav-link" href="{{url_for('client.show_home')}}">Home</a>
	</li>
	<li class="nav-item">
	  <a class="nav-link" href="{{url_for('authentication.logout')}}">Log Out</a>
	</li>
      </ul>
    </div>
  </nav>
</div>

<div>

<div class="line"></div>
    <div style="text-align: center;">
        <span style="font-size:24px;">Payment Successful</span>
    </div>
    
    <table border="2" cellpadding="3" cellspacing="1" align="center">
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Token ID</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{token_id}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Amount</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{final_price}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Paid by</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{pay_method}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
      <tr>
        <td style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>Exit Time</span>
        </td>
        <td bgcolor="#5DBCD2" style="text-align: center; font-size:24px; padding-left:20px; padding-right:20px">
            <span>{{exit_time}}</span>
            <!--<button type="button" class="btn btn-info" id="empty_slot">{{pl_empty_slots}}</button>-->
        </td>
      </tr>
    </table>

    <div class="input-group" style="margin-bottom:20px">
        <a class="nav-link" style="width:100%" href="{{url_for('client.show_home')}}">
          <button name="button" class="btn btn-primary btn-block">Print</button>
        </a>
    </div>


  </div>

{% endblock %}